project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "λ-исчисление"
  navbar: 
    left: 
      - index.html
      text: 'Главная'
      - docs/Lambda_vs_Turing.html
      text: 'Лямбда-исчисление и машина Тьюринга'
      - docs/lambda-calculus.html
      text: 'Лямбда-исчисление'
      - presentation/presentation.html
      text: 'Презентация'

editor: visual

