project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "λ-исчисление"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Главная"
        href: index.qmd
      - auto: "docs/*.qmd"
      - text: "Презентация"
        href: presentation/presentation.qmd
        

editor: visual

