# Системы типизации лямбда-исчисления

В лямбда-исчислении существуют различные системы типизации, которые определяют, какие термы являются корректными, а какие нет.

Системы типизации лямбда-исчисления можно разделить на следующие типы:

1.  Простая типизация
2.  Системы с подтипами
3.  Полиморфные системы
4.  Зависимые типы
5.  Системы с зависимыми типами

## Стили типизации

Есть два основных стиля типизации:

1.  Стиль Карри (Curry-style) - типы выводятся автоматически. Термы те же что и в бестиповом лямбда-исчислении. Каждый терм имеет своё множество типов: пустой множество, множество из одного типа или множество из нескольких типов или бесконечного множества типов. Типы не явно указываются в программе. Типы присваиваются (приписываются) термам.
2.  Стиль Чёрча (Church-style) - типы явно указываются в программе. Типы является неотъемлемой частью терма.

Встречается также такая терминология:

1.  Системы в стиле Карри — лямбда-исчисление с присваиваем типов.
2.  Системы в стиле Чёрча — системы типизированного лямбда-исчисления.

## Простая типизация (Simple type theory)

Простая типизация вводит только один тип для всех термов. В такой системе типизации каждый терм является либо атомом, либо абстракцией.

Простая типизация не позволяет корректно типизировать термы, которые используются в различных контекстах. Например, терм `λx.x x` не может быть типизирован в простой типизации.

Подробнее о простой типизации можно прочитать в [статье](./simple-type-theory.qmd).
