# Рекурсия

## Самореплицируемая функция

Рассмотрим следующую терм $\omega = λx.x\ x$.

``` text
w y = (λx.x x) y → y y
```

Применим его к самой себе:

``` text
w w = (λx.x x) (λx.x x) →
→ (λx.x x) (λx.x x) →
...
```

Этот процесс будет повторятся бесконечно. Процесс вычисления никогда не завершится.

Этот оператор имеет философское отношение к парадоксу Рассела или парадоксу Клини, когда объект, определяемый через сам себя, приводит к некорректности или бесконечности.

## Теорема неподвижной точки

Для любого λ-терма F существует неподвижная точка

$$
\forall F\ \exists X: F\ X = X
$$

### Доказательство

Введем - $W = λx. F (x x)$ - $X = W W$

Тогда

``` text
X = W W = (λx. F (x x)) W = F (W W) = F X
```

## Комбинатор неподвижной точки

Существует комбинатор неподвижной точки

``` text
Y = λf.(λx. f (x x))(λx. f (x x))
```

такой что $\forall F:\ F\ (Y\ F) = Y\ F$.

```         
Y F = 
(λx. F (x x))(λx. F (x x)) = 
F ((λx. F (x x))(λx. F (x x))) = 
F (Y X)
```

## Рекурсия. Определение факториала

Y-комбинатор позволяет ввести рекурсию в λ-исчисление.

Немного расширим ламбда-исчисление, чтобы показать как можно ввести рекурсивное определение факториала используя комбинатор неподвижной точки. Введем следующие функции

```         
PRED n — возвращает число предшествующее n
MULT n m — возвращает произведение n и m

ISZRO n — возвращает true, если n является 0
IIF (x, y, z) — функция сравнения, возвращает y, если x — true, иначе z
```

Тогда в этих определениях мы хотим написать определения факториала используя рекурсивный вызов.

```         
FAC = λn. IIF (ISZRO n) 1 (MULT n (FAC (PRED n)))
```

Но в лямбда-исчислении нельзя использовать саморефенцию для определения термов. Мы должны уметь развернуть каждое наше обозначения до базовых термов.

Чтобы решить эту проблему воспользуемся оператором неподвижной точки:

Перепишем с помощью абстракции

```         
FAC = (λf λn. IIF (ISZRO n) 1 (MULT n (f (PRED n)))) FAC
```

Обозначим `(λf. λn. IIF (ISZRO n) 1 (MULT n (f (PRED n))))` как `F`

```         
FAC = F FAC
```

Видно, что `FAC` — неподвижная точка функции `F`.

Тогда мы можем определить факториал следующим образом:

```         
FAC = Y F, где 
Y — комбинатор неподвижной точки,
F = λf. λn. IIF (ISZRO n) 1 (MULT n (f (PRED n)))
```

------------------------------------------------------------------------

Рекурсия в λ-исчислении реализуется через понятие неподвижной точки, позволяющей определить функции, вызывающие сами себя. Ключевую роль играет Y-комбинатор, который создает неподвижную точку для любой функции.

Это позволяет разрабатывать рекурсивные алгоритмы в рамках λ-исчисления, избегая прямой самореференции.